# Generated by Django 4.2.11 on 2024-03-18 00:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="question",
        ),
    ]
