# Generated by Django 4.2.11 on 2024-03-27 02:53

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0003_alter_quiz_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="user",
            field=models.ForeignKey(
                default=app.models.Quiz.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
